import { createSlice, type PayloadAction } from '@reduxjs/toolkit'
import type { SearchFilters } from '../types/Filter'
import type { SearchResult } from '../types/SearchResult'
const defaultFilters: SearchFilters = { categories: [], fileTypes: [], dateRange: 'any', relevance: 0 }
interface SearchState { query: string; results: SearchResult[]; filters: SearchFilters; loading: boolean; error: string | null; history: string[]; saved: string[]; understanding: string | null; relatedQuestions: string[]; selectedDocument: SearchResult | null }
const initialState: SearchState = { query: '', results: [], filters: defaultFilters, loading: false, error: null, history: ['Leave policy', 'Expense reimbursement', 'Remote work rules'], saved: ['HR policies', 'Engineering guidelines'], understanding: null, relatedQuestions: [], selectedDocument: null }
const searchSlice = createSlice({ name: 'semanticSearch', initialState, reducers: { setQuery: (state, action: PayloadAction<string>) => { state.query = action.payload }, setLoading: (state, action: PayloadAction<boolean>) => { state.loading = action.payload }, setFilters: (state, action: PayloadAction<SearchFilters>) => { state.filters = action.payload }, setResults: (state, action: PayloadAction<{ results: SearchResult[]; understanding: string; relatedQuestions: string[] }>) => { state.results = action.payload.results; state.understanding = action.payload.understanding; state.relatedQuestions = action.payload.relatedQuestions }, setError: (state, action: PayloadAction<string | null>) => { state.error = action.payload }, addHistory: (state, action: PayloadAction<string>) => { state.history = [action.payload, ...state.history.filter((item) => item !== action.payload)].slice(0, 5) }, clearHistory: (state) => { state.history = [] }, selectDocument: (state, action: PayloadAction<SearchResult | null>) => { state.selectedDocument = action.payload }, toggleSaved: (state, action: PayloadAction<string>) => { state.saved = state.saved.includes(action.payload) ? state.saved.filter((item) => item !== action.payload) : [...state.saved, action.payload] } } })
export const { setQuery, setLoading, setFilters, setResults, setError, addHistory, clearHistory, selectDocument, toggleSaved } = searchSlice.actions
export default searchSlice.reducer
